# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

    - { resource: "parameters.yml" }
    - { resource: "security.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/config.yml" }
parameters:
    locale: en_US

framework:
    translator: { fallbacks: ["%locale%", "en"] }
    secret: "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    session:
        handler_id: ~

doctrine:
    dbal:
        driver: "%database_driver%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        server_version: "9.6"
        charset: UTF8
        host: "%database_socket%"
        application_name: Sylius
doctrine_migrations:
    dir_name: "%kernel.project_dir%/app/migrations"
    namespace: Sylius\Migrations
    table_name: sylius_migrations
    name: Sylius Migrations

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    port: "%mailer_port%"
sylius_mailer:
    sender:
      name: Destro Machines
      address: support@destromachines.com
    emails:
        confirm_deposits:
            subject: "Please confirm the bank account you added to your Destro Machines account."
            template: ":Email:confirm_deposits.html.twig"
fos_rest:
    exception: true
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api/.*', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/web"
                cache_prefix: "media/cache"
    filter_sets:
        tagline_image:
            filters:
                # use and setup the "crop" filter
                crop:

                    # set the size of the cropping area w / h
                    size: [1631, 120]

                    # set the starting coordinates of the crop 450 570
                    start: [1, 450]
                # use and setup the "scale" filter
                scale:
                    # given 1920x1600px -> output 960x800px (relative down-scale)
                    to: 0.50
        hero_image:
            filters:
                # use and setup the "crop" filter
                crop:

                    # set the size of the cropping area w / h
                    size: [4240, 1854]

                    # set the starting coordinates of the crop
                    start: [1, 484]
            post_processors:
                    jpegoptim: { strip_all: true, max: 70, progressive: true }

fos_ck_editor:
    configs:
        my_config: