# DestroBundle/Resources/config/services.yml
imports:
    - { resource: services/mailer.yml }

services:
    sylius.controller.shop.contact: ~
    sylius.controller.shop.contact:
        class: DestroBundle\Controller\ContactController
        arguments: ['@router', '@form.factory', '@templating','@sylius.context.channel','@sylius.context.customer','@sylius.email_manager.contact']
    _defaults: { public: true }
    app.listener.admin.product_variant.form.menu_builder:
        class: DestroBundle\Menu\AdminProductVariantFormMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.product_variant.form, method: addItems }
    app.form.extension.type.product_variant:
        class: DestroBundle\Form\Extension\ProductVariantTypeExtraDimensionExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType, priority: -5 }
    app.form.extension.product_translation:
        class: DestroBundle\Form\Extension\ProductTranslationTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductTranslationType, priority: -5 }
    app.form.extension.page_translation:
        class: DestroBundle\Form\Extension\PageTranslationTypeExtension
        tags:
            - { name: form.type_extension, extended_type: BitBag\SyliusCmsPlugin\Form\Type\Translation\PageTranslationType, priority: -5 }
    app.form.extension.faq_translation:
        class: DestroBundle\Form\Extension\FrequentlyAskedQuestionTranslationTypeExtension
        tags:
            - { name: form.type_extension, extended_type: BitBag\SyliusCmsPlugin\Form\Type\Translation\FrequentlyAskedQuestionTranslationType, priority: -5 }
    app.google_cloud_storage_service_factory:
        class: DestroBundle\Factory\FileSystem\GoogleCloudStorageServiceFactory
    app.google_cloud_storage_service:
        class: \Google_Service_Storage
        factory: 'app.google_cloud_storage_service_factory:createService'
        arguments: ["%google_api.credentials_json%"]
    app.resolver.product_photos:
        class: DestroBundle\Factory\Resolver\GoogleStorageResolver
        arguments:
            - "@app.google_cloud_storage_service"
            - { Bucket : '%google_api.bucket%' , Directory : "sylius_image", Acl : "public" }
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'storage_cache_sylius_images' }
    app.delayed_email_sender:
        class: Sylius\Component\Mailer\Sender\Sender
        arguments: ['@sylius.email_renderer.adapter', '@app.email_sender.adapter.swiftmailer', '@sylius.email_provider', '@sylius.mailer.default_settings_provider']
    app.controller.stripe_ach_form:
        class: DestroBundle\Controller\StripeACH
        arguments: ['@sylius.repository.payment_method', '@app.delayed_email_sender', '@templating']
    app.listener.shop.menu_builder:
        class: DestroBundle\Menu\AccountMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }
    app.microdeposits.form.type:
        class: DestroBundle\Form\Type\MicroDepositsType
        tags:
            - { name: form.type }
    app.ach.form.type:
        class: DestroBundle\Form\Type\StripeACHType
        tags:
            - { name: form.type }
    sylius.payum_action.stripe_js.status:
        class: DestroBundle\Action\Stripe\StatusAction
        tags:
            - { name: payum.action, factory: stripe_js, alias: sylius.stripe_js.status }
    app.form.type.rule.contains_product_quantity_configuration:
        class: DestroBundle\Form\Type\Rule\ContainsProductQuantityConfigurationType
        arguments: ["@sylius.repository.product"]
        tags:
        - { name: form.type }
    app.rule_checker.contains_product_quantity:
        class: DestroBundle\Checker\Rule\ContainsProductQuantityRuleChecker
        tags:
        - { name: sylius.promotion_rule_checker, type: contains_product_quantity, form_type: DestroBundle\Form\Type\Rule\ContainsProductQuantityConfigurationType, label: Contains product quanitity }

