# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US
    google_api.credentials_json: '%kernel.root_dir%/../DestroMachinesStore-965e04f545e7.json'
    google_api.bucket: destromachinesstore_images