INSERT into DestroMachinesStore_dev.sylius_province (country_id, code, name, abbreviation)values 
(1, 'US-AL', 'Alabama', 'AL'),
(1, 'US-AK', 'Alaska', 'AK'),
(1, 'US-AZ', 'Arizona', 'AZ'),
(1, 'US-AR', 'Arkansas', 'AR'),
(1, 'US-CA', 'California', 'CA'),
(1, 'US-CO', 'Colorado', 'CO'),
(1, 'US-CT', 'Connecticut', 'CT'),
(1, 'US-DE', 'Delaware', 'DE'),
(1, 'US-DC', 'District of Columbia', 'DC'),
(1, 'US-FL', 'Florida','FL'),
(1, 'US-GA', 'Georgia','GA'),
(1, 'US-HI', 'Hawaii','HI'),
(1, 'US-ID', 'Idaho','ID'),
(1, 'US-IL', 'Illinois','IL'),
(1, 'US-IN', 'Indiana','IN'),
(1, 'US-IA', 'Iowa','IA'),
(1, 'US-KS', 'Kansas','KS'),
(1, 'US-KY', 'Kentucky','KY'),
(1, 'US-LA', 'Louisiana','LA'),
(1, 'US-ME', 'Maine','ME'),
(1, 'US-MD', 'Maryland','MD'),
(1, 'US-MA', 'Massachusetts','MA'),
(1, 'US-MI', 'Michigan','MI'),
(1, 'US-MN', 'Minnesota','MN'),
(1, 'US-MS', 'Mississippi','MS'),
(1, 'US-MO', 'Missouri','MO'),
(1, 'US-MT', 'Montana','MT'),
(1, 'US-NE', 'Nebraska','NE'),
(1, 'US-NV', 'Nevada','NV'),
(1, 'US-NH', 'New Hampshire','NH'),
(1, 'US-NJ', 'New Jersey','NJ'),
(1, 'US-NM', 'New Mexico','NM'),
(1, 'US-NY', 'New York','NY'),
(1, 'US-NC', 'North Carolina','NC'),
(1, 'US-ND', 'North Dakota','ND'),
(1, 'US-OH', 'Ohio','OH'),
(1, 'US-OK', 'Oklahoma','OK'),
(1, 'US-OR', 'Oregon','OR'),
(1, 'US-PA', 'Pennsylvania','PA'),
(1, 'US-PR',  'Puerto Rico','PR'),
(1, 'US-RI', 'Rhode Island','RI'),
(1, 'US-SC', 'South Carolina','SC'),
(1, 'US-SD', 'South Dakota','SD'),
(1, 'US-TN', 'Tennessee','TN'),
(1, 'US-TX', 'Texas','TX'),
(1, 'US-UT', 'Utah','UT'),
(1, 'US-VT', 'Vermont','VT'),
(1, 'US-VA', 'Virginia','VA'),
(1, 'US-WA', 'Washington','WA'),
(1, 'US-WV', 'West Virginia','WV'),
(1, 'US-WI', 'Wisconsin','WI'),
(1, 'US-WY', 'Wyoming','WY');